### ISSUE TITLE
joined.mean() returns NotImplementedError

### ISSUE THREAD

**Issue by mohanbolisetty** [ContinuumIO/blaze#1025]
Hello,

I am having issues with data after joining using blaze.join

```python
data_a = blaze.Data('file1.csv')
data_b = blaze.Data('file1.csv')

joined = blaze.join(data_a, data_b, ['med', 'time'])

joined.total_amount.mean()
<repr(<blaze.expr.reductions.mean at 0x7fb43061dfb0>) failed: NotImplementedError: >

blaze.__version__
'0.7.3'
```

Anything that I am doing wrong? The files are too large to load into my RAM using pandas to test if there is something wrong after merge. Running this within ipython 2.3.1

Thanks.

**Comment by llllllllll** [comment]
Thanks for the bug report @mohanbolisetty. What is the dtype of the column you are taking the mean of?

**Comment by llllllllll** [comment]
Are you still running into this with a newer version of blaze?

**Comment by mohanbolisetty** [comment]
Sorry, didn't see your message from June. I haven't tried blaze again since, I will upgrade tonight and give it a try. Thanks.

**Comment by llllllllll** [comment]
If things are still not working, could you upload the files so that I can try to investigate the issue?

**Comment by llllllllll** [comment]
I am going to close this as this was an older version of blaze and we have no repro case. If this is still affecting you, please feel free to comment and we will re-open the issue
