### ISSUE TITLE
Blaze can trigger crashes in the LLVM

### ISSUE THREAD

**Issue by cowlicks** [ContinuumIO/blaze#1030]
```python
import numpy as np
 
from odo import discover
from dask.array import from_array
from dask.array.blaze import compute, symbol
 
nx = np.arange(600).reshape((20, 30))
dx = from_array(nx, blockshape=(4, 5))
sx = symbol('x', discover(dx))
 
expr = sx.mean(axis=0)
 
dask_ns = {sx: dx}
 
result = compute(expr, dask_ns)
result2 = np.array(result)
print(result2)
```
We get the output
```bash
python crash_llvm.py 
python: LeaksContext.h:54: void llvm::LeakDetectorImpl<T>::addGarbage(const T*) [with T = llvm::Value]: Assertion `Ts.count(o) == 0 && "Object already in set!"' failed.
[1]    18320 abort      python test.py
```

**Comment by mrocklin** [comment]
This works fine if we operate without threads (e.g. using `result.compute(get=dask.async.get_sync)`) which supports the theory that this is due to simultaneous compilation.  @seibert @sklam we provide the signature to the function; is there a way to trigger the compilation before we have data for it?

**Comment by mrocklin** [comment]
Given the number of PRs that are blocking on this it might also make sense to remove this functionality from dask temporarily.

**Comment by gmarkall** [comment]
> we provide the signature to the function; is there a way to trigger the compilation before we have data for it?

You can do it with `compile_isolated` - assuming `func` is an undecorated Python function:

```python
from numba.compiler import compile_isolated

compiled_func = compile_isolated(func, sig).entry_point
```

Then call `compiled_func` where you would have called `func`.

The Numba dispatcher attempts to ensure that the compiler is not re-entered by another thread during compilation - if this is happening, then it could be a bug in Numba.

**Comment by gmarkall** [comment]
Whoops, I forgot that you are using `vectorize` - the way to compile a ufunc is to use a `UFuncBuilder`, e.g.:

```python
from numba.npyufunc.ufuncbuilder import UFuncBuilder

def myadd(a, b):
    return a + b
    
ufb = UFuncBuilder(myadd)

# cres will contain the CompileResult, if you want it
cres = ufb.add("int32(int32, int32)")
cres = ufb.add("int64(int64, int64)")

# ufunc is the compiled ufunc
ufunc = ufb.build_ufunc()
```
