### ISSUE TITLE
Can't import odo

### ISSUE THREAD

**Issue by dam5h** [ContinuumIO/blaze#1038]
I am simply trying to ```import odo``` and get the following traceback.  I searched for a bit but came up empty.  Any ideas?

```
<ipython-input-1-cf72f366607d> in <module>()
----> 1 import odo

/usr/lib/python2.7/site-packages/odo/__init__.py in <module>()
     38     from .backends.dynd import nd
     39 with ignoring(ImportError):
---> 40     from .backends import sql
     41 with ignoring(ImportError):
     42     from .backends import mongo

/usr/lib/python2.7/site-packages/odo/backends/sql.py in <module>()
     62 
     63 
---> 64 @discover.register(sa.sql.type_api.TypeEngine)
     65 def discover_typeengine(typ):
     66     if typ in revtypes:

AttributeError: 'module' object has no attribute 'type_api'


```

**Comment by cpcloud** [comment]
how are you installing blaze?

**Comment by cpcloud** [comment]
it also looks like you have an old version of sqlalchemy

**Comment by mrocklin** [comment]
We should probably have a more explicit requirements.txt that enforces versions on dependencies.  Installing `odo` with `pip` won't update dependencies by default.

**Comment by cpcloud** [comment]
there's an additional problem here, which is tracking down our usage of all the APIs and their minimum versions.

it'll probably make people unhappy if they have to use the latest version of everything

FWIW, this problem is a non-issue with `conda`.

**Comment by mrocklin** [comment]
> it'll probably make people unhappy if they have to use the latest version of everything

Maybe not?  I suspect that most people don't notice

**Comment by dam5h** [comment]
Updating SQLAlchemy from 0.7.2 to 1.0.0 via pip solved the issue.  Thank you for the rapid response!

I had initially installed blaze with pip but then cloned the repo directly here to see if that fixed the issue.

**Comment by cpcloud** [comment]
Cool. Glad it worked out for you! I'm going to update our requirements files to be correct wrt dependency versions.

**Comment by cpcloud** [comment]
I'll close the issue after I do that
