### ISSUE TITLE
Blaze server: 'Don't know how to compute'

### ISSUE THREAD

**Issue by llllllllll** [ContinuumIO/blaze#1043]
I am trying to use a blaze server to serve a `bz.Data` object that is wrapping a postgresql table; however, the server fails to do any computations.

My server configuration looks like:

```python
import blaze as bz
from sqlalchemy import create_engine, MetaData

engine = create_engine('postgresql://localhost/db')
bz.Server({
    'schema_table': bz.Data(MetaData(engine, schema='schema')['schema.table']),
}).run(host='0.0.0.0.', port=6363)
```

On the client, I am running:
```python
In [2]: ds = bz.Data('blaze://localhost:6363')

In [3]: ds
Out[3]: 
Data:       <blaze.server.client.Client object at 0x7f5137456828>
DataShape:  {
  schema_table: var * {
    knowledge_date: datetime,
    asof_date: datetime,
    open: ?float64,
    high: ?float64,
    low: ?float64,
  ...
```

However, if I try to do anything with this table, like: `ds.schema_table`, I get `ValueError: Bad response: INTERNAL SERVER ERROR`

I have the server route printing the error so I can see it, and I am getting:

```
Don't know how to compute:
expr: schema_table.head(11)
data: {schema_table:    knowledge_date  asof_date   open   high    low  close  volume
0      1990-01-02 1990-01-02  17.24  17.24  17.24  17.24       0   
1      1990-01-03 1990-01-03  18.19  18.19  18.19  18.19       0   
2      1990-01-04 1990-01-04  19.22  19.22  19.22  19.22       0   
```

If I act on the `bz.Data` object locally, without the server, it works as intended.

As a side note, is there a better way of specifying a data object to point to a single table in a non-default schema for postgres?

**Comment by mrocklin** [comment]
> As a side note, is there a better way of specifying a data object to point to a single table in a non-default schema for postgres?

Note that Blaze server is intended to work directly with data, not data wrapped up in `bz.Data`.  You could serve the table directly:

    t = sqlalchemy.Table('tablename', metadatat=..., autoload=True, ...)  # or something like this
    bz.Server(t).run(...) 

Ideally should also be able to serve the metadata directly.  I'm surprised that you needed to specify the 'schema.table' bit when creating the server

    bz.Server(MetaData(engine, schema='schema'))

The error you're getting sadly isn't helpful.  We should probably improve transmission of errors from the server through to the client.

**Comment by llllllllll** [comment]
Ah, serving the sqlalchemy Table object worked perfectly. Thank you for the quick response. Is there anything I can do to help get better messages to the client, or do you think that will be a larger project?

**Comment by mrocklin** [comment]
Looking at the code it looks like I tried this https://github.com/ContinuumIO/blaze/blob/master/blaze/server/server.py#L280-L283

```python
    try:
        result = compute(expr, {leaf: dataset})
    except Exception as e:
        return ("Computation failed with message:\n%s" % e, 500)
```

But this clearly hasn't been effective.

**Comment by llllllllll** [comment]
I will look into it a bit and see if I can clean up the error messaging. The line above the return is where I had to add a print to get the `Don't know hot to compute` message.

**Comment by llllllllll** [comment]
is it safe to close this issue?
