### ISSUE TITLE
test_mongo_compute.test_compute_on_db uses all my ram

### ISSUE THREAD

**Issue by llllllllll** [ContinuumIO/blaze#1052]
This test uses all of my ram (8GB), it spills into swap and then my computer locks up.
I setup an empty mongo for this to use and ran the admin command that is in the .travis.yml. I checked the developer workflow page; however, it didn't have a section about setting up the test database.

```
$ mongod --version
db version v2.6.8
2015-04-22T15:43:52.293-0400 git version: nogitversion
2015-04-22T15:43:52.293-0400 OpenSSL version: OpenSSL 1.0.2 22 Jan 2015
```

I am on Arch GNU+Linux

**Comment by cpcloud** [comment]
@llllllllll what version of pymongo are you using?

**Comment by llllllllll** [comment]
pymongo==3.0.1

**Comment by cowlicks** [comment]
This was happening to me a few days ago. But I didn't really give the issue due diligence because I was in "fix other stuff" mode. I was on debian testing, and I think I fixed it by upgrading to a more recent version of mongodb than what was in the repos.

**Comment by cpcloud** [comment]
@llllllllll can you try a more recent version of mongodb? Just want to see if it goes away with that.

**Comment by llllllllll** [comment]
```
$ mongod --version
db version v3.0.2
git version: nogitversion
OpenSSL version: OpenSSL 1.0.2 22 Jan 2015
```

same issue

**Comment by cpcloud** [comment]
ok cool, i'll take a tlook

**Comment by llllllllll** [comment]
Thanks

**Comment by llllllllll** [comment]
This is no longer happening, we can re-open if someone else has this issue.

I have upgraded a bunch of packages since this happened so something must have been out of date.

**Comment by cpcloud** [comment]
thanks!
