### ISSUE TITLE
Support pandas.DataFrame.query like Data Selection

### ISSUE THREAD

**Issue by jamartinh** [ContinuumIO/blaze#1067]
Hello, a very useful feature in Pandas is the possibility of doing selection based on the .query method of a dataframe. This allows for example to pass expressions as strings to specialized functions to filter data, which otherwise is not possible in an elegant way.

Please note the difference and economy in the code:

1) df.query('a > b')
2) df[df.a > df.b]  

Only by passing in (1) the name of the columns and the operator you express the selection. This, as mentioned above allows to pass 'a>b' as a string to a specialized function.

**Comment by llllllllll** [comment]
I always thought that the main reason for this feature in pandas was to prevent the creation of all of the intermediate data structures to allow for optimization of the whole query. Do you want this just for the more concise syntax?

**Comment by cpcloud** [comment]
In this case, blaze trades some elegance for the ability to optimize and implement a larger set of expressions across many different systems, including expressions like group by, join, and containment on backends as varied as pandas, sql, and spark.

I'm going to close this issue, as we're actively trying to avoid having to do string programming.
