### ISSUE TITLE
pypi page for blaze 0.8 displays raw markdown text

### ISSUE THREAD

**Issue by cowlicks** [ContinuumIO/blaze#1074]
https://pypi.python.org/pypi/blaze/0.8.0

**Comment by llllllllll** [comment]
pypi accepts reStructuredText not markdown. You can use [pandoc](https://hackage.haskell.org/package/pandoc) to do the conversion to a README.rst. github supports rending of a README.rst so it will not break.

**Comment by mrocklin** [comment]
There was some reason why I didn't do this.  I think that it was hard to
center the images appropriately or something.  Worth another go if anyone
is up for it.

**Comment by cpcloud** [comment]
I think not being able to read the docs on PyPI takes precedence over whether GitHub's RST renderer correctly aligns images
