### ISSUE TITLE
Blaze and Pandas HDF Clobbering?

### ISSUE THREAD

**Issue by quebbs** [ContinuumIO/blaze#1075]
I'm trying to create a simple HDF5 file with Pandas, which works fine if I ONLY import pandas, but when I import both Pandas and Blaze (and/or odo), the HDFStore fails.

    import pandas as pd
    import blaze as bz
    #from odo import odo #(this causes fail too)
    HStore=pd.HDFStore('MyStore.h5',mode='w')

I'm using W7, Anaconda, occurs on both Py27 and Py34, both in IPython and the Notebook, and all my packages are current.

	---------------------------------------------------------------------------
	HDF5ExtError                              Traceback (most recent call last)
	<ipython-input-3-6c2673b31a45> in <module>()
	----> 1 HStore=ps.HDFStore('MyFile.h5',mode='w')

	C:\Users\Jon Quebbeman\AppData\Local\Continuum\Anaconda\lib\site-packages\pandas\io\pytables.pyc in __init__(self, path, mode, complevel, complib, fletcher32, **kwargs)
		394         self._fletcher32 = fletcher32
		395         self._filters = None
	--> 396         self.open(mode=mode, **kwargs)
		397 
		398     @property

	C:\Users\Jon Quebbeman\AppData\Local\Continuum\Anaconda\lib\site-packages\pandas\io\pytables.pyc in open(self, mode, **kwargs)
		530 
		531         try:
	--> 532             self._handle = tables.open_file(self._path, self._mode, **kwargs)
		533         except (IOError) as e:  # pragma: no cover
		534             if 'can not be written' in str(e):

	C:\Users\Jon Quebbeman\AppData\Local\Continuum\Anaconda\lib\site-packages\tables\file.pyc in open_file(filename, mode, title, root_uep, filters, **kwargs)
		316 
		317     # Finally, create the File instance, and return it
	--> 318     return File(filename, mode, title, root_uep, filters, **kwargs)
		319 
		320 openFile = previous_api(open_file)

	C:\Users\Jon Quebbeman\AppData\Local\Continuum\Anaconda\lib\site-packages\tables\file.pyc in __init__(self, filename, mode, title, root_uep, filters, **kwargs)
		789 
		790         # Now, it is time to initialize the File extension
	--> 791         self._g_new(filename, mode, **params)
		792 
		793         # Check filters and set PyTables format version for new files.

	hdf5extension.pyx in tables.hdf5extension.File._g_new (tables\hdf5extension.c:4822)()

	HDF5ExtError: HDF5 error back trace

	  File "..\..\hdf5-1.8.14\src\H5F.c", line 507, in H5Fcreate
		not file access property list
	  File "..\..\hdf5-1.8.14\src\H5Pint.c", line 3331, in H5P_isa_class
		not a property list

	End of HDF5 error back trace

	Unable to open/create file 'MyFile.h5'

**Comment by mrocklin** [comment]
This sounds like the age-old conflict between the two dominant HDF5 Python
libraries, h5py and PyTables.  They don't like to be imported together,
especially on Windows.

Given that you want to use PyTables (used by pandas.HDFStore) you can
probably resolve this issue by importing tables before you import
blaze/odo.  This is kind of an ugly hack but is also the best solution I've
found to date.

**Comment by quebbs** [comment]
Indeed - adding `import tables` before blaze import does fix this. Thank you for the workaround.

**Comment by cpcloud** [comment]
closing
