### ISSUE TITLE
Data types change when using blaze.into()

### ISSUE THREAD

**Issue by TDaltonC** [ContinuumIO/blaze#1077]
I used blaze.into() to turn a blaze object into a pandas object [1] and the data types of some columns changes. 

```python
In [16]: recentUser.dshape
Out[16]: dshape("var * {_id: string, dateAdded: datetime, appID: string}")

In [17]: recentUserDF = bz.into(bz.DataFrame,recentUser)

In [18]: recentUserDF.dtypes
Out[18]: 
_id                  object
dateAdded    datetime64[ns]
appID                object
dtype: object
```

I was expecting that the default behavior would be that ``_id`` and ``appID`` would be strings. 

[1] this might be a dumb thing that no one should ever want to do. I needed to turn the blaze object into ``an iterable object such as a list, tuple or set`` so that I could use it as part of a subsequent ``.isin()`` query and this was the first thing that came to mind.

**Comment by cpcloud** [comment]
They are strings, it's just that pandas stores strings as numpy object arrays.

**Comment by TDaltonC** [comment]
Well, no problem then.
