### ISSUE TITLE
Simple deploy blaze-server with loaded data

### ISSUE THREAD

**Issue by chdoig** [ContinuumIO/blaze#1108]
From the roadmap meeting discussion: write a simple script to deploy blaze-server with loaded data from a directory.

Goal: Given a folder directory with data (any supported blaze backend) deploy a blaze-server with the data loaded in it.

Method:
For each file in the directory, run discover(uri) or Data(uri). If data can be discovered --> add data to server. e.g. Server(uri)

**Comment by mrocklin** [comment]
In pseudocode I would do something like the following

```python
resources = dict()
for fn in walk_directory_tree(directory):
    try:
        resources[fn] = resource(fn)
    except:
        pass

Server(resources).run()
```

Alternatively we could maintain the nested structure of the directory by treating each directory as a dict

```python
def dictify_directory(dir):
    resources = dict()
    for fn in os.listdir(dir):
        if os.path.isdir(fn):
            resources[fn] = dictify_directory(fn)
        else:
            try:
                resources[fn] = resource(fn)
            except:
                pass
    return resources
```

Alternatively again we could improve the `Directory` type to handle heterogeneous types and spider down automatically.

**Comment by mrocklin** [comment]
@cowlicks thoughts on trying this on?  My hope is that it's not much more complex than the `dictify_directory` function described above.

**Comment by cowlicks** [comment]
@mrocklin What/where is the `Directory` type?

**Comment by mrocklin** [comment]
It lives in Odo.  It is usually used as parametrized type like `Directory(CSV)` to mean a directory of CSV files.

Generally I wouldn't start with that.  I would start with a heterogenous directory with a few standard files in it of different types.  Perhaps the iris.csv file, an hdf5 file, and a subdirectory with a few json files.

The goal here isn't to solve a really hard problem but rather to show dumb-and-simple efficacy on simple-ish cases.  I would try-except on all files and just forget the ones that we can't trivially read.
