### ISSUE TITLE
add column names to compute.json response in blaze server

### ISSUE THREAD

**Issue by cpcloud** [ContinuumIO/blaze#1127]
xref: https://github.com/bokeh/bokeh/issues/2330

**Comment by llllllllll** [comment]
Does this need to be `json_format` specific?

**Comment by cpcloud** [comment]
No I think we should return the same dictionary of stuff no matter what the format js

**Comment by cpcloud** [comment]
Is*

**Comment by cpcloud** [comment]
I just put json there  because that was where the original stemmed
