### ISSUE TITLE
blaze.server does not allow CORS

### ISSUE THREAD

**Issue by fpliger** [ContinuumIO/blaze#1131]
`blaze.server` sticks with same origin policy so it does not enable CORS requests.. This is an issue for users using bokeh `BlazeDataSources` to map to a blaze server and update data directly on the browser without `bokeh.server` because this `blaze.server` (well, Flask default) configuration will raise an error. Something like:

```
  XMLHttpRequest cannot load http://domain:9000/compute.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://domain:5006' is therefore not allowed access.
```
.

This issue can be fixed by setting (injecting) the CORS policies on `blaze.server`. For instance:

```Python
        server = blaze.Server({'dat': gauss})
    
        def add_crossdomain_headers(response):
            response.headers.add('Access-Control-Allow-Origin', '*')
            response.headers.add('Access-Control-Allow-Methods', 'GET,POST')
            response.headers.add('Access-Control-Allow-Headers', "Origin, X-Requested-With, Content-Type, Accept")
    
            return response
    
        server.app.after_request(add_crossdomain_headers)
        server.run(host="127.0.0.1", port=9000)

```

But a probably better solution would be to have some kind of configuration on `blaze.server` itself so users don't have to bother too much trying to find the solution. 

NOTE: Flask does expose a `crossdomain` decorator that can be used to decorate views (and that may be a better solution) but I didn't figure out a quick way of using it within `blaze.server` before the views are declared (I may be overlooking something trivial, I honestly didn't have much time to dig in details).

**Comment by hhuuggoo** [comment]
I think the one we use in bokeh is a good

https://github.com/bokeh/bokeh/blob/master/bokeh/server/crossdomain.py

It's been modified from the original (http://flask.pocoo.org/snippets/56/)

To set access control allow headers to whatever was sent (if you set headers to None), so that differnet ajax pages which may have different default headers set don't break

**Comment by hhuuggoo** [comment]
For something like the blaze server - I think allowing crossdomain should be the default - since the blaze server doesn't have any web pages, any ajax request hitting the blaze server is always going to come from another domain

**Comment by cpcloud** [comment]
@fpliger @hhuuggoo it'd be nice to avoid duplication here. would it be reasonable to use this library http://flask-cors.readthedocs.org/en/latest/ to support crossdomain requests?

**Comment by cpcloud** [comment]
even simpler : https://github.com/iurisilvio/flask-crossdomain

**Comment by hhuuggoo** [comment]
I'm sure @tswicegood input would be good here, I think this line is important 

https://github.com/bokeh/bokeh/blob/master/bokeh/server/crossdomain.py#L48

and it's something we added, and is not in https://github.com/iurisilvio/flask-crossdomain

The reason I think it's important, is that it's nice to allow blaze server creators to not have to specify which headers they need to accept beforehand, and instead just allow arbitrary headers

**Comment by tswicegood** [comment]
I think if you want to enable CORS support on all requests as either a boolean, I would go with Flask-CORS and their [basic approach][1].  It does make sense for that to be the out-of-the-box behavior.

[1]: http://flask-cors.readthedocs.org/en/latest/#simple-usage

**Comment by fpliger** [comment]
> For something like the blaze server - I think allowing crossdomain should be the default - since the blaze server doesn't have any web pages, any ajax request hitting the blaze server is always going to come from another domain

Fully agree

> I think if you want to enable CORS support on all requests as either a boolean, I would go with Flask-CORS and their basic approach. It does make sense for that to be the out-of-the-box behavior.

ditto
