### ISSUE TITLE
Creating a column that contains NumPy arrays

### ISSUE THREAD

**Issue by gabrielelanaro** [ContinuumIO/blaze#1163]
I was wondering if blaze supports (or will support) the following usecase where a column is made of elements which are multidimensional arrays (In my case each row corresponds to the geometric state of a system, made of points with 3D coordinates each). So far I got the following error:

    data = bz.Data([[1, np.zeros(10, 3)],
                    [2, np.zeros(10, 3)],
                    [3, np.zeros(10, 3)]])
    
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-3-aef1ede857aa> in <module>()
    ----> 1 data = bz.Data([[1, np.zeros(10, 3)],
          2                 [2, np.zeros(10, 3)],
          3                 [3, np.zeros(10, 3)]])
    
    TypeError: data type not understood

**Comment by mrocklin** [comment]
The error that you're getting is from NumPy, not Blaze

```python
In [1]: import numpy as np

In [2]: np.zeros(10, 3)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-1c7629840d59> in <module>()
----> 1 np.zeros(10, 3)

TypeError: data type not understood

In [3]: np.zeros((10, 3))
Out[3]: 
array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])
```

But, after fixing this, Blaze still doesn't handle this case well.

**Comment by cpcloud** [comment]
@gabrielelanaro why wouldn't you use a N by 10 by 3 array for your use case?

**Comment by gabrielelanaro** [comment]
That's what I'm using right now in my code (with hdf5). The idea however is that the first dimension is "time". So we have those coordinates that evolve in time. Then, I'd like to add for example other properties that vary on a frame-by-frame basis:

    data = bz.Data([[1, np.zeros(10, 3), 0.0, np.zeros(10)],
                     [2, np.zeros(10, 3), 0.1, np.zeros(10)],
                     [3, np.zeros(10, 3), 0.2, np.zeros(10)], fields=['frame_no', 'coordinates', 'time', 'atomic_density']])

What I'm doing right now is storing all of those as separate arrays (there's also to say that those arrays are larger than memory). I believe http://xray.readthedocs.org/en/stable/ found a solution to the problem, but I have to try it yet.

**Comment by cpcloud** [comment]
After reading the `xray` overview, I think that it's likely better suited to your problem than blaze is. I haven't looked deeply into integrating xray with blaze, but i suspect it would be a large time investment. see the conversation here: https://github.com/ContinuumIO/dask/issues/326#issuecomment-113478480
