### ISSUE TITLE
Bcolz issues

### ISSUE THREAD

**Issue by blitzd** [ContinuumIO/blaze#1165]
Not sure if this is the same issue as #1007, but running a simple command like:

```into('pshare.bcolz', 'PShare-Rev2.csv', dshape=ds)```

crashes my python.exe kernel.

ds is a slightly modified dshape that came from discover on the same csv.

Same variation with odo causes the same kernel crash:

```odo.odo('PShare-Rev2.csv', 'pshare.bcolz', dshape=ds)```

This appears to be regardless of the values in ds, as it occurs without that parameter as well.

This is a csv that loads into a pandas dataframe just fine, but I was trying to get it into bcolz for parallel processing. 

This: 

```into('phones.bcolz', df, dshape=ds)```

Throws the error:

```ValueError: could not broadcast input array from shape (3,1048576) into shape (3)```

And this:

```odo.odo(df, 'phones.bcolz', dshape=ds)```

...again crashes the kernel.

**Comment by mrocklin** [comment]
What is your datashape, what does your data look like?

**Comment by blitzd** [comment]
dshape is like so:

ds = dshape("""var * {
  CID: int64,
  DefaultP: ?string,
  AID: ?string,
  RNo: ?string,
  PNo: ?string
  }""")

I can't post any of the actual data, but it's largely identifiers from a DB (int, CID/AID), a phone number (DefaultP, max len=25), and some shorter 4 to 5 digit int numbers that can be null (RNo, PNo). I defaulted most oft he values to string since they can be null.

**Comment by mrocklin** [comment]
What I find odd is that your array has shape `(3, n)` rather than `(n,)`.  I'll assume that you're using a `carray` then and not a `ctable`?  If so then is there a reason?

**Comment by blitzd** [comment]
I'm not specifically defining anything like that, I just have a CSV that I am trying to get into a bcolz format. Any shape that it's come up with is being inferred by what I was doing above.

I also managed to get the CSV into a Data() object, where I thought I was getting further, but then when trying:

```odo.odo(d, 'ph.bcolz', dshape=ds)```

I again get:

```ValueError: could not broadcast input array from shape (3,1048576) into shape (3)```

That does produce about 2GB worth of data before it results in that error though - which is also interesting, since the CSV itself is 800MB.

**Comment by mrocklin** [comment]
Regarding the data blowup I suspect you're running into issues with object dtype.  Suggest reading http://odo.pydata.org/en/latest/datashape.html?highlight=object#datatypes-increase-efficiency 

I'm not sure how much we can help without knowing at least a little bit about your data.  The fact tha tyou have a 2d shape implies that something strange is going on.  I'd be curious at what stage in your ingestion pipeline that occured.

**Comment by blitzd** [comment]
Not sure if this is a connected issue, but trying to reduce the amount of data to just 100 rows of my dataset I ran into this, and here's the smallest re-creation I can come up with:

a.csv:

```CID,TxtCol,AID,RNo,PNo
123,Abc,123,99999,9999
123,Abc,123,99999,9999
123,Abc,123,99999,9999
123,Abc,123,99999,9999
123,Abc,123,99999,9999
123,Abc,123,99999,9999
123,Abc,123,99999,9999
123,Abc,123,99999,9999
123,Abc,123,99999,9999
123,Abc,123,99999,9999```

```ds = dshape("""var * {
  CID: int64,
  DefaultP: string,
  AID: int64,
  RNo: ?int32,
  PNo: ?int32
  }""")

a = Data('a.csv', dshape=ds)

a```

And then:

```into('a.bcolz', a, dshape=ds)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
C:\Anaconda3\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    688                 type_pprinters=self.type_printers,
    689                 deferred_pprinters=self.deferred_printers)
--> 690             printer.pretty(obj)
    691             printer.flush()
    692             return stream.getvalue()

C:\Anaconda3\lib\site-packages\IPython\lib\pretty.py in pretty(self, obj)
    407                             if callable(meth):
    408                                 return meth(obj, self, cycle)
--> 409             return _default_pprint(obj, self, cycle)
    410         finally:
    411             self.end_group()

C:\Anaconda3\lib\site-packages\IPython\lib\pretty.py in _default_pprint(obj, p, cycle)
    527     if _safe_getattr(klass, '__repr__', None) not in _baseclass_reprs:
    528         # A user-provided repr. Find newlines and replace them with p.break_()
--> 529         _repr_pprint(obj, p, cycle)
    530         return
    531     p.begin_group(1, '<')

C:\Anaconda3\lib\site-packages\IPython\lib\pretty.py in _repr_pprint(obj, p, cycle)
    709     """A pprint that just redirects to the normal repr function."""
    710     # Find newlines and replace them with p.break_()
--> 711     output = repr(obj)
    712     for idx,output_line in enumerate(output.splitlines()):
    713         if idx:

C:\Anaconda3\lib\site-packages\bcolz\ctable.py in __repr__(self)
   1244         if self.rootdir:
   1245             header += "  rootdir := '%s'\n" % self.rootdir
-> 1246         fullrepr = header + str(self)
   1247         return fullrepr
   1248 

C:\Anaconda3\lib\site-packages\bcolz\ctable.py in __str__(self)
   1232 
   1233     def __str__(self):
-> 1234         return array2string(self)
   1235 
   1236     def __repr__(self):

C:\Anaconda3\lib\site-packages\bcolz\arrayprint.py in array2string(a, max_line_width, precision, suppress_small, separator, prefix, style, formatter)
    466     else:
    467         lst = _array2string(a, max_line_width, precision, suppress_small,
--> 468                             separator, prefix, formatter=formatter)
    469     return lst
    470 

C:\Anaconda3\lib\site-packages\bcolz\arrayprint.py in _array2string(a, max_line_width, precision, suppress_small, separator, prefix, formatter)
    338     lst = _formatArray(a, format_function, len(a.shape), max_line_width,
    339                        next_line_prefix, separator,
--> 340                        _summaryEdgeItems, summary_insert)[:-1]
    341     return lst
    342 

C:\Anaconda3\lib\site-packages\bcolz\arrayprint.py in _formatArray(a, format_function, rank, max_line_len, next_line_prefix, separator, edge_items, summary_insert)
    512 
    513         for i in xrange(trailing_items, 1, -1):
--> 514             word = format_function(a[-i]) + separator
    515             s, line = _extendLine(s, line, word, max_line_len,
    516                                   next_line_prefix)

C:\Anaconda3\lib\site-packages\bcolz\ctable.py in __getitem__(self, key)
   1046             ra = self._arr1.copy()
   1047             # Fill it
-> 1048             ra[0] = tuple([self.cols[name][key] for name in self.names])
   1049             return ra[0]
   1050         # Slices

C:\Anaconda3\lib\site-packages\bcolz\ctable.py in <listcomp>(.0)
   1046             ra = self._arr1.copy()
   1047             # Fill it
-> 1048             ra[0] = tuple([self.cols[name][key] for name in self.names])
   1049             return ra[0]
   1050         # Slices

bcolz\carray_ext.pyx in bcolz.carray_ext.carray.__getitem__ (bcolz\carray_ext.c:23271)()

bcolz\carray_ext.pyx in bcolz.carray_ext.carray.getitem_object (bcolz\carray_ext.c:22840)()

bcolz\carray_ext.pyx in bcolz.carray_ext.chunks.__getitem__ (bcolz\carray_ext.c:9736)()

bcolz\carray_ext.pyx in bcolz.carray_ext.chunks.read_chunk (bcolz\carray_ext.c:9284)()

ValueError: chunkfile a.bcolz\DefaultP\data\__-9.blp not found
```

If running it when the a.bcolz directory already exists, the kernel then dies.

**Comment by cpcloud** [comment]
Object dtypes are very poorly supported in bcolz. You need to provide a fixed length string type to put strings into bcolz. In the next odo release we are going to raise an error when someone tries to use object dtypes with bcolz

**Comment by cpcloud** [comment]
see this issue https://github.com/ContinuumIO/odo/issues/181

**Comment by blitzd** [comment]
That appears to have been the issue - with specifying the dshape type on the string as [25, "ascii"] it will now go into the bcolz format. I did also see the data climb up to over 3GB, but it's appears to have applied compression afterwards so it's now down to 240MB!

**Comment by cpcloud** [comment]
nice, can we close this issue?

**Comment by blitzd** [comment]
For sure, thanks!
