### ISSUE TITLE
blaze.interactive.InteractiveSymbol.tail(n)

### ISSUE THREAD

**Issue by scls19fr** [ContinuumIO/blaze#1184]
Hello,

I'm new to blaze.

I'm connecting to a MySQL Database table

![capture d ecran 2015-07-22 a 21 50 33](https://cloud.githubusercontent.com/assets/109167/8835591/c0346316-30bb-11e5-9919-1dfc20aa672b.png)

    import blaze as bz
    uri = 'mysql+mysqlconnector://user:password@127.0.0.1:3306/meteo::data'
    dat = bz.Data(uri)

There is

    dat.head(5)

but no

    dat.tail(5)

Moreover `dat[:5]` provide first 5 rows

but `dat[-5:]` raises `ValueError: start value of slice cannot be negative with a SQL backend`

I can get this "tail"... but that's not very convenient (compared to Pandas)

    dat[int(dat.count())-5:int(dat.count())]

That's also odd to see that

    dat[dat.count()-5:dat.count()]

return nothing.

Sorry for my newbies questions

Kind regards

**Comment by llllllllll** [comment]
You can do:

```python
dat.sort(ascending=False).head(5)
```

**Comment by llllllllll** [comment]
To go into more detail, the use of a negative slice was not implemented because we are using limits and offsets to implement slicing in the first place which do not support a negative slice. One idea would be to implement it with the `.count() - n` trick. Note that this is an extremely inneficient operation in sql. If you need to do a lot of slicing, I would suggest odoing your dataset into another format first. 

About the slice returning nothing, what do you mean by that?
Did it return an empty data set?
I get the results that I expect when testing against postgres (I don't have a mysql instance to test on)

```python
In [1]: raw = pd.DataFrame(np.arange(15).reshape(5, 3), columns=list('abc'))

In [2]: raw
Out[2]: 
    a   b   c
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14

In [3]: tbl = odo(raw, resource('postgresql://localhost/test::test', dshape=discover(raw)))

In [4]: ds = bz.Data(tbl)

In [5]: ds[ds.count() - 2:]
/home/joejev/quantopian/blaze/blaze/compute/sql.py:856: UserWarning: The order of the result set from a Slice expression computed against the SQL backend is not deterministic.
  warnings.warn('The order of the result set from a Slice expression '
Out[5]: 
    a   b   c
0   9  10  11
1  12  13  14
```

Note the warning, this operation can basically return any 2 tuples and still follow the sql standard.

**Comment by scls19fr** [comment]
In [193]: dat[dat.count()-5:dat.count()]
    Out[193]:

**Comment by llllllllll** [comment]
Can you show me the results of:

`repr(dat[dat.count()-5:dat.count()])`

**Comment by femtotrader** [comment]
In [195]: repr(dat[dat.count()-5:dat.count()])
    ---------------------------------------------------------------------------
    NotImplementedError                       Traceback (most recent call last)
    <ipython-input-195-9447906ce71f> in <module>()
    ----> 1 repr(dat[dat.count()-5:dat.count()])

    //anaconda/lib/python3.4/site-packages/blaze/interactive.py in expr_repr(expr, n)
        255
        256     # Scalars
    --> 257     if ndim(expr) == 0 and isscalar(expr.dshape):
        258         return repr(coerce_scalar(compute(expr), str(expr.dshape)))
        259

    //anaconda/lib/python3.4/site-packages/blaze/expr/expressions.py in ndim(expr)
        782     2
        783     """
    --> 784     return len(shape(expr))
        785
        786

    //anaconda/lib/python3.4/site-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
        162             self._cache[types] = func
        163         try:
    --> 164             return func(*args, **kwargs)
        165
        166         except MDNotImplementedError:

    //anaconda/lib/python3.4/site-packages/blaze/expr/expressions.py in shape(expr)
        766     (2, 2)
        767     """
    --> 768     s = list(discover(expr).shape)
        769     for i, elem in enumerate(s):
        770         try:

    //anaconda/lib/python3.4/site-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
        162             self._cache[types] = func
        163         try:
    --> 164             return func(*args, **kwargs)
        165
        166         except MDNotImplementedError:

    //anaconda/lib/python3.4/site-packages/blaze/expr/expressions.py in discover(expr)
        808 @dispatch(Expr)
        809 def discover(expr):
    --> 810     return expr.dshape

    //anaconda/lib/python3.4/site-packages/blaze/expr/expressions.py in dshape(self)
        430     @property
        431     def dshape(self):
    --> 432         return self._child.dshape.subshape[self.index]
        433
        434     @property

    //anaconda/lib/python3.4/site-packages/datashape/internal_utils.py in __getitem__(self, key)
         27
         28     def __getitem__(self, key):
    ---> 29         return self.fn(key)
         30
         31

    //anaconda/lib/python3.4/site-packages/datashape/coretypes.py in _subshape(self, index)
        695                 return 1 * self._subshape(index[1:])
        696             elif len(index) == 1:
    --> 697                 return self._subshape(index[0])
        698             else:
        699                 ds = self.subarray(1)._subshape(index[1:])

    //anaconda/lib/python3.4/site-packages/datashape/coretypes.py in _subshape(self, index)
        685                     count = var
        686
    --> 687             if count != var and index.step is not None:
        688                 count = int(ceil(count / index.step))
        689

    //anaconda/lib/python3.4/site-packages/blaze/expr/core.py in __ne__(self, other)
        140
        141     def __ne__(self, other):
    --> 142         return self._ne(other)
        143
        144     def __lt__(self, other):

    //anaconda/lib/python3.4/site-packages/blaze/expr/arithmetic.py in _bin(self, other)
        300     def _bin(self, other):
        301         result = cons(self, scalar_coerce(self.dshape, other))
    --> 302         result.dshape  # Check that shapes and dtypes match up
        303         return result
        304     _bin.__name__ = prefix + name

    //anaconda/lib/python3.4/site-packages/blaze/expr/arithmetic.py in dshape(self)
        156     def dshape(self):
        157         # TODO: better inference.  e.g. int + int -> int
    --> 158         return DataShape(*(maxshape([shape(self.lhs), shape(self.rhs)]) +
        159                            (self._dtype,)))
        160

    //anaconda/lib/python3.4/site-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
        162             self._cache[types] = func
        163         try:
    --> 164             return func(*args, **kwargs)
        165
        166         except MDNotImplementedError:

    //anaconda/lib/python3.4/site-packages/blaze/expr/expressions.py in shape(expr)
        766     (2, 2)
        767     """
    --> 768     s = list(discover(expr).shape)
        769     for i, elem in enumerate(s):
        770         try:

    //anaconda/lib/python3.4/site-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
        162             self._cache[types] = func
        163         try:
    --> 164             return func(*args, **kwargs)
        165
        166         except MDNotImplementedError:

    //anaconda/lib/python3.4/site-packages/datashape/discovery.py in discover(o, **kwargs)
         52         return from_numpy(o.shape, o.dtype)
         53     raise NotImplementedError("Don't know how to discover type %r" %
    ---> 54                               type(o).__name__)
         55
         56

    NotImplementedError: Don't know how to discover type 'Var'

**Comment by llllllllll** [comment]
Sorry, what is the version of `blaze.__version__`?

**Comment by scls19fr** [comment]
In [207]: blaze.__version__
  Out[207]: 'unknown'

???

**Comment by llllllllll** [comment]
Did you install blaze through conda, pip, or just git clone. The first thing I would do is try to update blaze to the most recent version with whatever means you used to install it. I am not sure what would cause the `__version__` to be 'unknown'

**Comment by llllllllll** [comment]
Okay, I see you are using conda, I personally haven't installed blaze with conda so I am not sure why that would report as unknown. Are you able to perform any operations on your `dat` object?

For example, does just evaluatiing `dat` work? does `dat[dat.count() - 2:]` work?

**Comment by scls19fr** [comment]
I removed Conda version and installed `'0.8.2+63.g0350f4b'` using:

    $ pip install git+git://github.com/ContinuumIO/blaze

I still facing

    NotImplementedError: Don't know how to discover type 'Var'

with `repr(dat[dat.count()-5:dat.count()])`


    In [12]: dat[dat.count() - 2:]
    //anaconda/lib/python3.4/site-packages/blaze/compute/sql.py:856: UserWarning: The order of the result set from a Slice expression computed against the SQL backend is not deterministic.
      warnings.warn('The order of the result set from a Slice expression '
    Out[12]:
                Timestamp  direction_Vmin  direction_Vmoy  direction_Vmax  Vmin  \
    0 2015-06-02 07:50:03             147             246             292   2.4
    1 2015-06-02 08:00:03             192             251             282   3.1

       Vmoy  Vmax    Ta    HR      Pa  ...    Intensite_P  Accumulation_G  \
    0  10.2  24.1  19.5  51.0  1003.7  ...              0               0
    1  11.4  20.5  19.5  52.3  1003.6  ...              0               0

       Duree_G  Intensite_G  Intensite_P_max  Intensite_G_max  Tchauffage  \
    0        0            0                0                0        22.1
    1        0            0                0                0        22.0

       Uchauffage  Ualim   Uref
    0          15   15.2  3.501
    1          15   15.2  3.501

    [2 rows x 22 columns]

**Comment by llllllllll** [comment]
Well, if this works without the second bound, then that is morally equivalent; however, we should still look into this. I will open a seperate issue so that we can discuss the addition of a `tail` method here.

**Comment by llllllllll** [comment]
This expression type was added in #1187

**Comment by scls19fr** [comment]
Thanks

**Comment by scls19fr** [comment]
I've just installed blaze from git

    In [16]: dat.head(5)
    Out[16]:
                Timestamp  direction_Vmin  direction_Vmoy  direction_Vmax  Vmin  \
    0 2011-03-07 16:30:03              56              91             131   2.3
    1 2011-03-16 16:00:03             337              58             135   1.0
    2 2011-03-16 15:50:03              52              60              74   1.9
    3 2011-03-16 15:40:03              33              54              64   2.6
    4 2011-03-16 15:30:03              18              62              97   3.4

       Vmoy  Vmax    Ta    HR      Pa  ...    Intensite_P  Accumulation_G  \
    0   3.6   6.4  10.3  51.4  1006.5  ...              0               0
    1   2.1   4.5  15.7  60.0   987.4  ...              0               0
    2   3.5   4.8  15.8  59.2   987.3  ...              0               0
    3   5.6   7.8  15.9  58.8   987.2  ...              0               0
    4   5.0   7.2  16.0  57.6   987.1  ...              0               0

       Duree_G  Intensite_G  Intensite_P_max  Intensite_G_max  Tchauffage  \
    0        0            0             37.2                0         9.2
    1        0            0             39.9                0        15.2
    2        0            0             39.9                0        15.2
    3        0            0             39.9                0        15.4
    4        0            0             39.9                0        15.6

       Uchauffage  Ualim   Uref
    0          15   15.3  3.503
    1          15   15.2  3.502
    2          15   15.2  3.503
    3          15   15.2  3.502
    4          15   15.3  3.503

    [5 rows x 22 columns]

    In [17]: dat.tail(10)
    Out[17]:

nothing is displayed

**Comment by scls19fr** [comment]
I also noticed:

    #!/usr/bin/env python

    import blaze as bz
    from blaze import odo, chunks
    import pandas as pd

    def main():
        table_uri = 'mysql+mysqlconnector://root:root@127.0.0.1:3306/meteo::data'
        dat = bz.Data(table_uri)
        print(dat)
        print(dat.head(10))
        print(dat.tail(10))

    if __name__ == '__main__':
        main()

Running script returns

    $ python blaze_example.py
    _1
    _1.head(10)
    _1.tail(10)

**Comment by llllllllll** [comment]
@scls19fr As I meantioned, there is no sql implementation and your interactive symbol is wrapping a sql database.

For the second comment, printing an expression is the same as calling `str` on it. This does not force the computation but instead shows the full expression that will be evaluated. You can force the computation with `blaze.compute`. To simulate the behavior from the repl, you can call `repr` on it which is the same as `blaze.compute(expr.head(11))`

**Comment by scls19fr** [comment]
I just wonder if you can't get tail using a limit and an offset (and reversing on Python side result).
