### ISSUE TITLE
iterrows (by chunk)

### ISSUE THREAD

**Issue by femtotrader** [ContinuumIO/blaze#1185]
Hello,

I noticed that with blaze it's possible to iterate by rows.

    In [200]: for row in dat[0:10]:
        print(row)

tuples are print
maybe an `iterrows` method should be create (like Pandas).

it could yields

an integer and a dict (or a pd.Series like)

`iterrows` could have a chunksize parameter.

It will be very useful if data is too big.

Kind regards

**Comment by llllllllll** [comment]
You can already get this functionality through odo:

```python
In [1]: ds = bz.Data('postgresql://localhost/test::test')

In [2]: ds
Out[2]: 
    a   b   c
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14

In [3]: for chunk in odo(ds, chunks(pd.DataFrame), chunksize=2): print(chunk)
   a  b  c
0  0  1  2
1  3  4  5
   a   b   c
2  6   7   8
3  9  10  11
    a   b   c
4  12  13  14
```

Generally things that involve data conversion live in odo

**Comment by femtotrader** [comment]
I wonder if it doesn't convert to a DataFrame and after iterates over rows ?

**Comment by llllllllll** [comment]
Maybe I misunderstood, how would your proposed `iterrows` work differently than the current iteration protocol or the code I showed?

**Comment by femtotrader** [comment]
My idea is to iterate over slices of a big table (as `blaze.expr.expressions.Slice`) and to iterate over rows of slices

Not sure I'm clear enough

The goal is to quickly start process (no to put data in memory) even with a very big table

**Comment by llllllllll** [comment]
with the `odo(..., chunks(pd.DataFrame))` you would only ever have one chunk in memory at a time. If you want them as symbols, you can `map(Data, odo(...))`. Some computation would need to happen to know how many elements to yield, otherwise it would yield slices that are no longer in the dataset.

**Comment by femtotrader** [comment]
Compare with a big table (200000 rows for example)

    # (very) long at startup

    for i, chunk in enumerate(odo(dat, chunks(pd.DataFrame), chunksize=10)):
        print("chunk %d" % (i + 1))
        for i, row in chunk.iterrows():
            print(row)

with

    # Short at startup

    def iterrows(dat, chunksize):
        n = int(dat.nrows)
        i = 0
        while(i<n):
            slice = dat[i:i + chunksize]
            for row in slice:
                yield(row)
            i += chunksize

    for row in iterrows(dat, 10):
        print(row)

I still need some improvement to have row a dict like.

**Comment by llllllllll** [comment]
Why is the first one long at startup, it lazily reads from the database and yields as soon as 1 dataframe is ready

**Comment by femtotrader** [comment]
I don't think so... try to change chunsize. Even with a very low value of chunksize it's very long to see first rows.

**Comment by femtotrader** [comment]
sorry you may be true.

**Comment by llllllllll** [comment]
I know that there was an issue that some database iterator paths would pull data eagerly; so this might actually be slow due to another bug.
