### ISSUE TITLE
A Blaze equivalent for: SELECT * WHERE t.column IN list_values

### ISSUE THREAD

**Issue by chdoig** [ContinuumIO/blaze#637]
I'd like to have a way to select rows from values in a given list without a Join hack. ;)

An equivalent to SQL:
SELECT * WHERE t.column IN list_values

**Comment by TomAugspurger** [comment]
Just to piggy-back on this issue, an is *not* in operation would be useful too. Right now it seems difficult to recast `not_isin` as a join, like you can (always?) do with `isin`.

```python
In [42]: df1 = pd.DataFrame({'A': [1, 2, 3, 4], 'B': ['a', 'b', 'c', 'd']})

In [43]: df2 = pd.DataFrame({'A': [3, 4, 5]})

In [44]: d1 = Data(df1)

In [45]: d2 = Data(df2)
```

I'm not sure of the best way to get the rows of of `d1` where 'A' is not in `d2` (rows 0 and 1).
With SQL it's something like

```sql
select d1.*
from d1
left join d2
  on d1.a = d2.a
where d2.a is null
order by a;
```

With blaze, a `join(d1, d2, how='left')`, I don't have a chance to add the `where` clause.

I guess this is an anti-join? I'm not too familiar with the relational algebra. Maybe this warrants a new issue/API?

**Comment by cpcloud** [comment]
I think using `join` for this computation is overkill in the case that we want to check membership against a small list of values. For example,

```python
t.column.isin(['a', 'b', 'c'])
```

`['a', 'b', 'c']` isn't a table, so co-opting join in the case would be awkward. Certainly in the case of `t.column.isin(s.column)` we could use join for backends where this expression would be difficult to implement.

**Comment by mrocklin** [comment]
Yeah, I guess I was thinking of `isin` as more of a binary operator with some other expression as in `A[A.column.isin(B.column)]` (though presumably this spelling could be improved).  In that case leveraging `join` is likely computationally ideal.

I'm not sure how to cleanly do the small number of elements case.

**Comment by mrocklin** [comment]
Looks like I was over-thinking it.  I was unaware of `SELECT ... WHERE ... IN ...` statements in SQL
