### ISSUE TITLE
Datetime access in SQL databases

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/blaze#711]
@cpcloud recently added some datetime access expressions.  These don't yet lower to SQLAlchemy.  

Spending a couple minutes googling it looks like this might be hard to do generally 
http://stackoverflow.com/questions/3371292/way-to-query-database-with-sqlalchemy-where-a-date-is-a-particular-day-of-the-we

Further investigation is warranted.  I suspect that this would be of significant value.

We could lower to each dialect individually.  This might not be worth the added complexity at this stage of development (SQL needs to remain as nimble as possible).

The right answer to this issue may be "It's not time yet".

**Comment by cpcloud** [comment]
implemented by #1003
