### ISSUE TITLE
backend: SAS support

### ISSUE THREAD

**Issue by jreback** [ContinuumIO/blaze#763]
some issues that I have come across

http://stackoverflow.com/questions/14262433/large-data-work-flows-using-pandas/14268804?noredirect=1#comment41493838_14268804 (see last comment)

https://github.com/pydata/pandas/issues/4052

blaze would be really helpful here

As best bet ATM is to chunk export from sas (might be proprietary)
as csv and then to hdf5

**Comment by cpcloud** [comment]
this is really something for [`into`](https://github.com/ContinuumIO/into)

**Comment by cpcloud** [comment]
going to move there
