### ISSUE TITLE
API: translations

### ISSUE THREAD

**Issue by jreback** [ContinuumIO/blaze#810]
So blaze goes from a python expression -> backend execution

would be interesting from a user perspective to be able to do this in reverse as well.

e.g. ``select * from table where amount < 0`` -> ``t[t.amount<0]``

I think particularly for SQL this would be most interesting as users could then take their existing sql
expressions and generate blaze expressions (and/or drive the back end)

e.g. use SQL to drive pandas/bcolz/PySpark etc.....

AND

might want to reverse of this type of string generation - to be able to generate actual SQL from a blaze expression. 

So then you can do things like translate SQL -> Q ! whoo hoo.
(this 2nd part is not THAT interesting, but maybe useful for testing).

**Comment by cpcloud** [comment]
i believe someone from hammerlab asked about this today

**Comment by cpcloud** [comment]
i think making blaze parse sql is out of scope
