### ISSUE TITLE
Compute map on numpy arrays should build numba functions

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/blaze#834]
We have types through datashape.  We should be able to translate these to the numba type system and then jit on the fly.

**Comment by cpcloud** [comment]
@mrocklin is the `map` in the title here referring to `Map` expressions or is this closed by #909

**Comment by mrocklin** [comment]
Map expressions.  If someone already has a Python function that is numba-able then maybe we should numba-it for them.

**Comment by cpcloud** [comment]
we do this now as of #909 

pretty huge speedup vs no numba

```
In [1]: x = np.arange(1e8)
t ^P

In [2]: t = symbol('t', discover(x))

In [3]: timeit r = compute(t.map(lambda x: x + 1, 'float64'), x)
1 loops, best of 3: 360 ms per loop

In [4]: timeit -n1 -r1 r = compute(t.map(lambda x: x + 1, 'float64'), x, optimize=False)
1 loops, best of 1: 45 s per loop

In [5]: 45000/360
Out[5]: 125.0
```

**Comment by cpcloud** [comment]
going to add a test here
