### ISSUE TITLE
blaze 0.7.0 requires toolz 7.1, cytoolz 7.2dev

### ISSUE THREAD

**Issue by jreback** [ContinuumIO/blaze#894]
these need to be indicated in meta.yaml (or remove tail from the direct imports)

**Comment by cpcloud** [comment]
@jreback @mrocklin can this be closed? we seem to be using the right versions of `toolz` all around ...

**Comment by cpcloud** [comment]
closing as we have the proper versions. pls reopen if there's still an issue
