### ISSUE TITLE
hash(expr) != hash(expr2) does not imply that expr.isidentical(expr2) is False

### ISSUE THREAD

**Issue by cpcloud** [ContinuumIO/blaze#912]
somewhat esoteric bug where a `._subs(...)` call isn't substituting the correct values because this predicate is testing `True` when it should be `False` here: https://github.com/ContinuumIO/blaze/blob/master/blaze/compute/core.py#L352-L353

```
ipdb> inputs
[Broadcast(_children=(chunk.a, chunk.b), _scalars=(a, b), _scalar_expr=a < b)]
ipdb> exprs
(Broadcast(_children=(a, b), _scalars=(a, b), _scalar_expr=a < b),)
ipdb> hash(inputs[0]) == hash(exprs[0])
False
ipdb> inputs[0].isidentical(exprs[0])
True
```

**Comment by cpcloud** [comment]
here's the issue: a `tuple` of `Expr`s will compare `True`, because `tuple`s recursively compare their elements with `==`. The `__eq__`  of `Expr`s will always return a `True`y thing. I the solution is to call `isidentical` recursively

**Comment by cpcloud** [comment]
more specifically,

```python
    def __bool__(self):
        return True
```

causes an expr like `a == b` to be `True` when it's an element of a `tuple`. For example,

```python
(a,) == (b,)
```
I think this will *always* test `True` for any expression.

**Comment by cpcloud** [comment]
and just to beat a dead horse, we have this:

```
ipdb> exprs[0]
Broadcast(_children=(a, b), _scalars=(a, b), _scalar_expr=a < b)
ipdb> exprs[0]._scalar_expr
a < b
ipdb> (exprs[0],) == (exprs[0]._scalar_expr,)
True
```

**Comment by mrocklin** [comment]
Defining `isidentical` recursively sounds like a good solution.  Thanks for tracking this down.

**Comment by cpcloud** [comment]
@mrocklin good news: this will be fixed in my numba PR

any particular reason for multiplying certain expressions by `1.0`?

```
ipdb> agg_expr
summary(a=sum(aggregate.a), b=((1.0 * sum(aggregate.b_total)) / sum(aggregate.b_count)) + 1)
ipdb> expected
summary(a=sum(aggregate.a), b=(sum(aggregate.b_total) / sum(aggregate.b_count)) + 1)
```

We're already using `truediv` for `Div` expressions, so integer vs. float division shouldn't be a problem.

**Comment by mrocklin** [comment]
My guess is that I ran into a case where we weren't using truediv well.  I'd be happy if I were wrong though.
