### ISSUE TITLE
multi-criteria selection fails

### ISSUE THREAD

**Issue by ARF1** [ContinuumIO/blaze#960]
I am probably using the selection operator wrongly but the following syntax returns incorrect results: (If the syntax is indeed invalid, I think an error should be thrown.)

```
In [2]: from blaze import TableSymbol, compute
   ...: accounts = TableSymbol('accounts', '{id: int, name: string, amount: int}')
   ...: deadbeats = accounts[accounts.name == 'Alice' or accounts.name == 'Dennis']
   ...: 
   ...: L = [[1, 'Alice',   100],
   ...:      [2, 'Alice',   -200],
   ...:      [3, 'Charlie', 300],
   ...:      [4, 'Dennis',  400],
   ...:      [5, 'Edith',  -500]]
   ...: 
   ...: list(compute(deadbeats, L))
```
```
Out[2]: [[1, 'Alice', 100], [2, 'Alice', -200]]
```
It should output:
```
Out[2]: [[1, 'Alice', 100], [2, 'Alice', -200], [4, 'Dennis',  400]]
```
Version used:
```
In [5]: blaze.__version__
Out[5]: '0.7.0'
```
BTW: How does one formulate multi-criteria selections correctly?

**Comment by mrocklin** [comment]
This is actually a pure python issue.  `or` must return either `True` or `False` so in this case your query becomes the following:

* Before: `accounts[accounts.name == 'Alice' or accounts.name == 'Dennis']`
* After: `accounts[True]`

There is nothing Blaze (nor numpy nor pandas) is able to do here.  Instead you need to use the bitwise or operator, `|`.  Beware with this as the order of operations is not what most people expect.  You'll need to parenthesize both sides around the `|`.

    accounts[(accounts.name == 'Alice') | (accounts.name == 'Dennis')]

This is unfortunate and would be a nice change to suggest to the core language developers for Python 3.5.

**Comment by cpcloud** [comment]
FYI, overloadable boolean operators was a PEP

http://legacy.python.org/dev/peps/pep-0335/

and was rejected:

https://mail.python.org/pipermail/python-dev/2012-March/117510.html

**Comment by cpcloud** [comment]
The guy actually patched his implementation into Python and you can download it http://www.cosc.canterbury.ac.nz/~greg/python/obo//Python_OBO.tar.gz here

**Comment by ARF1** [comment]
@mrocklin Thank you for explaining. I suppose, there is then no trace of the `or` operator being used that could be detected in the `key` argument of `__getitem__` either?

From your explanation is seems as if a check for `key == True` or `isinstance(key, bool)` could be used to issue a warning to the user that he was probably doing something wrong in the first place.

That would help new users get started, advanced users could be given the option of disabling the warning if there are legitimate uses of something like `accounts[True]`...
