### ISSUE TITLE
Selection with NOT operator

### ISSUE THREAD

**Issue by ARF1** [ContinuumIO/blaze#961]
It would be nice if it was possible to use the selection with an inversion operator allowing concise selection of all field except the one defined.

Something along the lines of:
```
df[['~col1', '~col2']]
```
or
```
df[~['col1', 'col2']]
```

**Comment by mrocklin** [comment]
Looks like you're asking for something like `dplyr`'s `-col` syntax.  We can do this with strings as you've done in your example.  This could be part of either the getitem syntax or a separate `select` function.  

Personally I rarely need this syntax.  Is this something that you often find yourself using / wanting?  If so I'd be curious what the use case is (just for my own personal curiosity)

This might also be something to think about in Pandas land cc @jreback

**Comment by jreback** [comment]
we use

``df.drop(['col1','col2'])`` in pandas

**Comment by ARF1** [comment]
@mrocklin
I have a something like a transactional database / transaction log: It contains 3 "natural index columns", 11 data column and a time-stamp column for the entry and a 'validUntil' column that indicates until when the entry is valid.

A common usage is to get the state of the database at an arbitrary point in time:
```
db = somebackend
d = blaze.Data(db)

# get state of database at a particular point in time (2015-01-26T20:15:46.339000)
# i.e. all entries entered before the timestamp, which are still valid at the time stamp
a = db[(d.validUntil >= '2015-01-26T20:15:46.339000') &
      (d.timeStamp <= '2015-01-26T20:15:46.339000')][['-validUntil', '-timestamp']

**Comment by cpcloud** [comment]
@ARF1 we don't have syntax for this right now, but you don't have to explicitly list all the columns you want, just the ones you don't:

```python
cond = ((d.validUntil >= '2015-01-26T20:15:46.339000') &
        (d.timeStamp <= '2015-01-26T20:15:46.339000'))
d[cond][[field for field in d.fields if field not in ('validUntil', 'timeStamp')]]
```

**Comment by cpcloud** [comment]
@ARF1 I'm going to close this as I don't think we'll implement this. I'll offer another suggestion instead :)

You could define a function `without` that takes the `Data` instance as the first argument and the columns to ignore as the second argument:

```python
def without(data, ignore):
    return data[[field for field in data.fields if field not in ignore]]
```
You could use it like this:

```python
result = without(d[cond], ['validUntil', 'timeStamp'])
```
