### ISSUE TITLE
Allow setting default for map parameter of compute()

### ISSUE THREAD

**Issue by ARF1** [ContinuumIO/blaze#964]
It would be nice if it was possible to set a default value for the map parameter of the compute command.

Currently I am always specifying `compute(..., map=pool.map)`. Just specifying `compute(...)` would be cleaner.

I tried setting `blaze.map = pool.map` but this does not seem to have the desired effect.

**Comment by mrocklin** [comment]
That seems like a good idea.  Under this sort of approach one could even do away with the explicit call to `compute` and (if one only needs to see the results) just rely on the `repr`, which would give a cleaner user experience.

**Comment by mrocklin** [comment]
Does the solution in https://github.com/ContinuumIO/blaze/pull/965 resolve this for you @ARF1 ?
