### ISSUE TITLE
The .fields attribute should be empty on non-record datashapes

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/blaze#966]
We currently have a default `fields` attribute even on datasets with a homogenous datashape 

```python
In [1]: import blaze as bz

In [2]: bz.Data([1, 2, 3]).fields
Out[2]: ['_1']
```

This should probably just be `[]`

cc @fpliger

**Comment by cpcloud** [comment]
+1 on empty list

**Comment by mrocklin** [comment]
I agree that this makes sense.  It's probably just a bunch of straightforward work to ensure that we're not relying on this behavior anywhere.

**Comment by fpliger** [comment]
\o/ thanks!
