### ISSUE TITLE
remove dummy classes from optional backends

### ISSUE THREAD

**Issue by cpcloud** [ContinuumIO/blaze#967]
A recent PR was merged to `py.test` to allow doctests to skip on `ImportError`. We've been working around this by making dummy classes.

https://bitbucket.org/hpk42/pytest/pull-request/243/add-option-to-ignore-import-errors-in/diff

things that need to be updated for testing:

1. `.binstar.yml`
2. `.travis.yml`
3. should probably add `--doctest-skip-import-errors` to a `pytest.ini` file in the blaze repo

backends that do this (feel free to add to this list):

* mongodb
* spark + sparksql

**Comment by mrocklin** [comment]
Is there a py.test release cycle that we should be aware of?  We should probably bump the py.test version dependency as we do this.

**Comment by cpcloud** [comment]
closed by c03f3b65af045d753ee14aa9c0d38ee39219b5e1
