### ISSUE TITLE
Union Operation

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/blaze#974]
Sometimes we want to union several tables together to form one large table.  Some things to think about

1.  Expressions with an indeterminate number of inputs are always a bit tricky.  This came up in `Broadcast`
2.  For some backends, like SQL, this is straightforward (there is a UNION sqlalchemy term), but for others, like a bunch of different CSV files or a mix of various backends things do become a bit tricky.  This might be a good opportunity for parallelism but we'll have to manage the `compute_up`/`compute_down` dance well.

**Comment by notestaff** [comment]
"Union" might not be the right name for the operation, as row order matters unlike in SQL union.
VStack seems more accurate.

**Comment by llllllllll** [comment]
#1128 adds this operation
