### ISSUE TITLE
Bug converting expr with np.asarray

### ISSUE THREAD

**Issue by fpliger** [ContinuumIO/blaze#984]
Expressions created seem to no be correctly converted using `np.array`. See Out[113] of the following code:

```Python
In[82]: vs = {'first': [2., 5., 3.], 'second': [4., 1., 4.], 'third': [6., 4., 3.]}
In[83]: vdf = pd.DataFrame(vs)
In[109]: v1 = blaze.Data(vdf, fields=["A", "B", "C"])
In[110]: v1
Out[110]: 
   first  second  third
0      2       4      6
1      5       1      4
2      3       4      3
In[111]: v2 = blaze.Data(vdf)
In[112]: v2
Out[112]: 
   first  second  third
0      2       4      6
1      5       1      4
2      3       4      3
In[113]: np.asarray(v1)
Out[113]: 
array([(0.0, 0.0, 0.0), (0.0, 0.0, 0.0), (0.0, 0.0, 0.0)], 
      dtype=[('A', '<f8'), ('B', '<f8'), ('C', '<f8')])
In[114]: np.asarray(v2)
Out[114]: 
array([(2.0, 4.0, 6.0), (5.0, 1.0, 4.0), (3.0, 4.0, 3.0)], 
      dtype=[('first', '<f8'), ('second', '<f8'), ('third', '<f8')])
In[115]: blaze.into(pd.DataFrame, v1)
Out[115]: 
   first  second  third
0      2       4      6
1      5       1      4
2      3       4      3
In[116]: blaze.into(pd.DataFrame, v2)
Out[116]: 
   first  second  third
0      2       4      6
1      5       1      4
2      3       4      3
```

**Comment by fpliger** [comment]
Thinking a bit more about that, I may be misunderstanding the `fields` argument, how it's supposed to be used and the difference with `columns`

**Comment by cpcloud** [comment]
Columns is the deprecated version of fields. They do the same thing, it's just that fields is a little more generic. Since blaze handles databases where things are not called columns, such as a mongodb, we decided on using fields for this purpose.

**Comment by cpcloud** [comment]
It also looks like there could be an issue here. I can take a look today.

**Comment by cpcloud** [comment]
Note that passing in fields will not change the underlying data. We could certainly be much mor explicit about this in the docs while simultaneously pointing people to relabel expressions.

**Comment by fpliger** [comment]
Thanks for the explanation. Actually I was confused about fields being actually a metadata replacement or just convenience aliasing.

**Comment by mrocklin** [comment]
You don't need to use fields/columns.  It's there to provide extra data for data sources that don't name things.  Your dataframe is completely self-describing, so you don't need fields/columns.  You should just do the following

    d = Data(my_dataframe)

The fact that this is silently ignored is an error though.

**Comment by fpliger** [comment]
:+1:  IMO the main issue is really the output from np.asarray() being entirely different.

**Comment by mrocklin** [comment]
Ah, yes, I glossed over that part while reading.  The two issues are related though.  Everything works fine if the field names match up.  I think the right thing to do here is to err when fields is used unnecessarily. 

```python
In [1]: vs = {'first': [2., 5., 3.], 'second': [4., 1., 4.], 'third': [6., 4., 3.]}

In [2]: import pandas as pd

In [3]: vdf = pd.DataFrame(vs)

In [4]: from blaze import Data

In [5]: d = Data(vdf)

In [6]: d
Out[6]: 
   first  second  third
0      2       4      6
1      5       1      4
2      3       4      3

In [7]: import numpy as np

In [8]: np.asarray(d)
Out[8]: 
array([(2.0, 4.0, 6.0), (5.0, 1.0, 4.0), (3.0, 4.0, 3.0)], 
      dtype=[('first', '<f8'), ('second', '<f8'), ('third', '<f8')])

In [9]: d = Data(vdf, fields=['a', 'b', 'c'])

In [10]: np.asarray(d)
Out[10]: 
array([(0.0, 0.0, 0.0), (0.0, 0.0, 0.0), (0.0, 0.0, 0.0)], 
      dtype=[('a', '<f8'), ('b', '<f8'), ('c', '<f8')])
```
