### ISSUE TITLE
head() on HDFStore seems to try to load everything?

### ISSUE THREAD

**Issue by michaelaye** [ContinuumIO/blaze#986]
I am trying to learn how to work with blaze on a 12 GB pandas HDFStore file.
After having learned that I need to use ' hdfstore://' in front of the filename because pandas uses a different format (could be mentioned a bit more prominent in the tutorials), I tried a `head()` call on the blaze.Data object. I was expecting that it stops loading the HDF file after some count like 10..30 rows but my memory monitor jumps up to 2 GB used fast, so apparently it tries to load everything?
Wouldn't it be a design goal of blaze to avoid loading everything, unless that's not possible (yet?) with pandas HDFStores?
Here's the commands I used:
```python
dbfile = get_current_database_fname()
import blaze as bz
p4data = bz.Data( 'hdfstore://'+dbfile+'::df')
p4data.head()
```
I confirmed with a p4data.columns that all the content is recognized correctly:
```python
p4data.columns
['classification_id',
 'created_at',
 'image_id',
 'image_name',
 'image_url',
 'user_name',
 'marking',
 'x_tile',
 'y_tile',
 'acquisition_date',
 'local_mars_time',
 'x',
 'y',
 'image_x',
 'image_y',
 'radius_1',
 'radius_2',
 'distance',
 'angle',
 'spread',
 'version',
 'user_agent']
```

Am I doing something wrong or is there an incompatibility?

Versions:
blaze: 0.7.2
pandas: '0.15.2-318-g549b72f'

**Comment by mrocklin** [comment]
The default options on HDFStore store data in a way such that can not be loaded incrementally.  (at least I don't know how).  Here is an example using straight Pandas.

```Python
In [1]: import pandas as pd

In [2]: df = pd.DataFrame({'text': ['Alice', 'Bob', 'Charlie', 'Dan'], 'numbers': [1, 2, 3, 4]})

In [3]: df
Out[3]: 
   numbers     text
0        1    Alice
1        2      Bob
2        3  Charlie
3        4      Dan

In [4]: df.to_hdf('foo.hdf5', 'bar')

In [5]: pd.read_hdf('foo.hdf5', 'bar', start=0, stop=2)
Out[5]: 
   numbers     text
0        1    Alice
1        2      Bob
2        3  Charlie
3        4      Dan

In [6]: pd.read_hdf('foo.hdf5', 'bar', chunksize=2)
TypeError: can only use an iterator or chunksize on a table
```

In general I think you'll have a much better experience if you add the `format='table'` option to `to_hdf`.  This stores data in a a much more partitionable way, and will enable both partial loads as well as chunked operation.

It's very hard to work with the default HDFStores.  I would welcome knowledge on better ways to handle them.

**Comment by mrocklin** [comment]
Can you recommend where we should put information on the `hdfstore://` protocol to improve user experience?

**Comment by michaelaye** [comment]
This file is in `table` format:
```python
<class 'pandas.io.pytables.HDFStore'>
File path: /Users/klay6683/data/planet4/2015-03-08_planet_four_classifications_queryable.h5
/df            frame_table  (typ->appendable,nrows->12110427,ncols->22,indexers->[index],dc->[classification_id,image_id,image_name,user_name,marking,acquisition_date,local_mars_time])
```

So, could blaze not wrap the <start=0, stop=2> part of pd.read_hdf? I thought that was kinda the idea of blaze?

**Comment by michaelaye** [comment]
In http://nbviewer.ipython.org/github/mrocklin/blaze-tutorial/blob/master/01-into-Introduction.ipynb
I would put a mini-section for the most used datatypes, you already often have an example for SQL and CSV files, adding one for pandas HDFStores (unless you want to avoid to explicitly support them) would be nice, where it becomes immediately clear how to work with it. Currently, that knowledge is hidden in the middle of the `The :: separator` markdown section at the end of the tutorial.

**Comment by mrocklin** [comment]
> So, could blaze not wrap the start=0, stop=2 part of pd.read_hdf? I thought that was kinda the idea of blaze?

Blaze does wrap something like `pd.read_hdf` my example above was showing how these don't work for FixedFrame formats, which apparently you don't have.  When you interact with tabular format hdfstores it chunks up the dataset into pieces.  Looking [here](https://github.com/ContinuumIO/odo/blob/master/odo/backends/hdfstore.py#L38-L40) my guess is that our default chunksize is just too large.  Two possible improvements

1.  I suspect that we could take that down an order of magnitude and still do quite well.  
2.  In other systems we often try to emit a first small chunk followed by several large ones.  This is specifically for `head` queries, which are quite common due to the way we `repr`.  Probably we should do that here.

So I suspect that it actually was chunking up your dataset and not loading it all in to memory.  It's just that the chunks were sufficiently large that it appeared to be loading everything in.

**Comment by mrocklin** [comment]
Perhaps we should link more prominently to the odo/into docs.  http://odo.readthedocs.org/en/latest/hdf5.html

**Comment by michaelaye** [comment]
I even don't know what `odo` is as it's not mentioned in any of the tutorials [here](https://github.com/ContinuumIO/blaze-tutorial).

**Comment by mrocklin** [comment]
Into was recently renamed to odo.

**Comment by mrocklin** [comment]
I believe that https://github.com/ContinuumIO/odo/pull/127 might resolve this problem.

**Comment by mrocklin** [comment]
> I even don't know what odo is as it's not mentioned in any of the tutorials here.

Thank you for the reminder to update those tutorials when we do the next Blaze release.

**Comment by michaelaye** [comment]
Wow, fast, thanks! And in the `conda` `blaze` channel I get these updates as well? Or do you recommend going via github?

**Comment by mrocklin** [comment]
Either should work although for the moment it looks like our OS-X build boxes are down.  If you're going the conda route check here to see when the build is complete.

I would do either

    conda install blaze-core -c blaze
    pip install git+https://github.com/ContinuumIO/blaze

As always, thank you for the feedback.  This small change should hopefully improve user experience on large HDF5 files in pandas format nicely.  I've closed this issue.  If anything continues to be amiss please feel free to reopen it.

**Comment by michaelaye** [comment]
If I were to change my saving format of my large Pandas data frame, what format would you recommend to work better with blaze?

**Comment by mrocklin** [comment]
They all get translated into iterators of DataFrames in the end.  There isn't much difference from our end.
