### ISSUE TITLE
Using blaze within IPython notebooks

### ISSUE THREAD

**Issue by michaelaye** [ContinuumIO/blaze#987]
I noticed that memory is not released somewhere when I'm using blaze inside an IPython notebook (v3.0.0):

Doing this on a 12 GB HDFStore file:

```python
import blaze as bz
p4data = bz.Data( 'hdfstore://'+dbfile+'::df')
p4data.x.mean()
```
I see the process going up and down in memory consumption, which I expected to, maybe reading things in chunks, but unfortunately when done, it stays at a memory size of 6 GB. I assume this might be due to the notebooks internal caching? Is there a workaround?

Using Python 3.4.

**Comment by mrocklin** [comment]
Maybe?  Maybe garbage collection?  What is the result after calling

```python
import gc
gc.collect()
```

As in my comment on https://github.com/ContinuumIO/blaze/issues/986 the vanilla hdfstore format is a bit wonky.  You might have a better experience if you use the `format='table'` option to `to_hdf` (or just create your data with `odo/into` which will do this by default)

**Comment by michaelaye** [comment]
Interestingly, in this try I 'only' had a 800 MB Python process, and after the gc.collect() it went down to the standard 300 MB so maybe this was a hickup or an OSX thing, as I was doing other things in the background which might have forced a cleanup to get more memory?

**Comment by mrocklin** [comment]
The bliss of ignorance that comes with garbage collection.  Closing.

**Comment by michaelaye** [comment]
I'm not sure that it's okay to close this. I just did a `head()` on the HDFStore file, waiting for it to finish, and am again still stuck with a 2.26 GB memory consumption from this, even though I did not store any object in the notebook. That shouldn't be like that, I think.

**Comment by mrocklin** [comment]
Hrm, can you provide a minimum failing example?  Here is what I've been working with 

```python
In [1]: import pandas as pd

In [2]: import numpy as np

In [3]: df = pd.DataFrame({'text': ['Alice', 'Bob', 'Charlie', 'Dan'] * (10000000/4), 'numbers': np.random.random(10000000)})

In [4]: df.to_hdf('foo.hdf5', 'x', format='table')

In [5]: from blaze import Data

In [6]: x = Data('hdfstore://foo.hdf5::x')

In [7]: x
Out[7]: 
     numbers     text
0   0.478519    Alice
1   0.412291      Bob
2   0.922639  Charlie
3   0.144997      Dan
4   0.596155    Alice
5   0.684483      Bob
6   0.804322  Charlie
7   0.733773      Dan
8   0.827111    Alice
9   0.690719      Bob
...

In [8]: %timeit repr(x)
100 loops, best of 3: 16.5 ms per loop
```

**Comment by michaelaye** [comment]
Can u merge the cells so that I can copy/paste it? Thx.

**Comment by michaelaye** [comment]
Maybe related:
```python
dshape("""12110427 * {
  classification_id: ?string,
  created_at: ?datetime,
  image_id: ?string,
  image_name: ?string,
  image_url: ?string,
  user_name: ?string,
  marking: ?string,
  x_tile: int64,
  y_tile: int64,
  acquisition_date: ?datetime,
  local_mars_time: ?string,
  x: ?float64,
  y: ?float64,
  image_x: ?float64,
  image_y: ?float64,
  radius_1: ?float64,
  radius_2: ?float64,
  distance: ?float64,
  angle: ?float64,
  spread: ?float64,
  version: ?float64
  }""")
```
Why do all types have a question mark?

**Comment by mrocklin** [comment]
I'm sorry I don't understand what you mean by merge the cells.  I just did this in the console.  You might have to do a slight amount of editing as you copy-paste.

Types have question marks if they may contain missing values.  The way pandas treats strings/floats they may always contain missing values.  You may want to read through http://datashape.pydata.org/

**Comment by michaelaye** [comment]
I meant to merge your inputs to one notebook cell, but luckily (and cool as it is), the notebook doesn't care about it so copy/paste just worked, apart from one thing: I'm using Python3 and your division results in a float there which can't be used as a multiplier, so I had to use `//`:

```python
In [3]: df = pd.DataFrame({'text': ['Alice', 'Bob', 'Charlie', 'Dan'] * (10000000//4),
                           'numbers': np.random.random(10000000)})
```
Now, the bad news:

```python
%timeit repr(x)
1 loops, best of 3: 20.1 s per loop
```
How can it be soo much worse?

The memory consumption rose and stayed from 445 MB to 982 MB after doing the %timeit.

**Comment by mrocklin** [comment]
Can you verify that you're using the updated version?

**Comment by michaelaye** [comment]
```bash
$ conda install blaze-core -c blaze
Fetching package metadata: ......
Solving package specifications: ...............
# All requested packages already installed.
# packages in environment at /Users/klay6683/miniconda3:
#
blaze-core                0.7.2               np19py34_86
```

```python
blaze.__version__
'0.7.2'
```

**Comment by mrocklin** [comment]
Most recent build is 88.  I'll assume that you're on a Mac.  Note that our mac build box is down for the moment.  You'll have to install from source, either using pip pointed to the github repo or python setup.py install directly.

**Comment by michaelaye** [comment]
I used the pip git+https route. Had to use `--upgrade` to ignore the existing blaze install.
It automatically downgraded by pandas to 0.15.2. Last line of that install says:
```bash
Successfully installed blaze-0.7.2 pandas-0.15.2 python-dateutil-2.4.1 pytz-2014.10 sqlalchemy-0.9.9
```
But when calling `blaze.__version__` I still get 0.7.2? Can you include a build number to the version string to make these more obvious? My result is still:
```python
1 loops, best of 3: 19.7 s per loop
```

**Comment by michaelaye** [comment]
Wow, blaze parses the CSV file for a column.mean() test faster than getting the same from HDF file, I might as well stay with the original delivered CSV file. ;)

**Comment by mrocklin** [comment]
Try updating `odo` as well.  That was where the chunksize change came from.  My apologies, I should have directed you to this at the onset.

    pip install --upgrade git+https://github.com/ContinuumIO/odo


> Can you include a build number to the version string to make these more obvious?

Are you interested in contributing this?  It seems like you have a clear idea of what should happen here.

**Comment by michaelaye** [comment]
BTW, using `odo` to convert a HDFStore into a CSV and doing that inside a notebook also leaves me with a 2.3 GB python process in memory. I bet this is related to the notebook's internal caching.

**Comment by michaelaye** [comment]
yay, with the updated `odo` it's beating your numbers! ;)

```python
100 loops, best of 3: 9.58 ms per loop
```
on an iMac 5K.

**Comment by mrocklin** [comment]
Glad to hear it.  OK to close?

**Comment by michaelaye** [comment]
Up to you. I still think somebody needs to work on the fact that when working inside IPython notebooks, one encounters invisible memory leaks. I call them invisible, because when I would assign objects to variables, I would at least understand that I have a cached item. But if all I do is an odo conversion without any local storage, and my Python task grows from 140 MB to 1.2 GB (just confirmed with the updated odo), I start to worry.

**Comment by mrocklin** [comment]
This could be either garbage collection or ipython caching, neither of which are within scope but both of which do tend to behave sanely.  I would expect both the python garbage collector and ipython caching to clear out and respond to memory pressure.  If not then those should be resolved upstream.  You might want to raise this in a more general way on the IPython issue list.

Closing for now.
