### ISSUE TITLE
sep parameter ignored when opening a 'csv' file

### ISSUE THREAD

**Issue by maxgrenderjones** [ContinuumIO/blaze#991]
`blaze.__version__=0.7.2`
`into.__version__=0.2.2`
As a pandas user, I'm used to passing `sep=` to specify the separator when opening a `.csv` file, and the `.csv`s I receive are all semi-colon separated.

However, 
```python
>>> d=Data('filename.csv', sep=';', encoding='utf8')
```
fails, but
```python
d=Data('filename.csv', delimiter=';', encoding='utf8')
```
succeeds.

I've tracked the issue down to `into.backends.csv._csv_to_DataFrame` by hacking in a `print` statement:
```python
    print('Separator: %s' % sep)
    return pandas.read_csv(c.path,
                             header=header,
                             sep=sep,
                             encoding=encoding,
                             dtype=dtypes,
                             parse_dates=parse_dates,
                             names=names,
                             compression=compression,
                             chunksize=chunksize,
                             usecols=usecols,
                             **kwargs2)
```
In the `sep` case, it prints `,` but in the delimiter case it prints `;`.

`sep` is set in the line below (from `into.backends.csv._csv_to_DataFrame`):
```python
sep = kwargs.pop('sep', kwargs.pop('delimiter', c.dialect.get('delimiter', ',')))
```
which looks right, unless somehow `sep` doesn't get passed through?

**Comment by mrocklin** [comment]
Hrm, odd.  Thanks for the detailed fail report.  Will take a look shortly.

**Comment by mrocklin** [comment]
Hi @maxgrenderjones I think that was resolved in https://github.com/ContinuumIO/odo/issues/142 .  I've closed this issue for now.  If this doesn't resolve your issue then please do reopen.

**Comment by mrocklin** [comment]
And thanks for reporting.
