### ISSUE TITLE
expose a global queue of the durations of the last N calls to compute

### ISSUE THREAD

**Issue by cpcloud** [ContinuumIO/blaze#993]
```python
import time
from Queue import Queue

times = Queue(maxsize=10)

def compute(expr, data):
    start = time.time()
    # ...
    dur = time.time() - start
    times.put({expr: dur})
```

I suspect this will be trickier in the case of backends that use SQLAlchemy

**Comment by mrocklin** [comment]
Yeah, I've actually tried to stop compute and post_compute from actually triggering work, instead pushing that all the way down to the call to `odo` (e.g. `sqlalchemy.Select` -> `list`).  Addtionally it's common for compute calls to call other compute calls.  In general I think that the goal of recording "how long did that thing that I just ran take?" would be better suited to IPython than to Blaze.

**Comment by cpcloud** [comment]
closing as out of scope for blaze
