### ISSUE TITLE
ImportError: cannot import name 'SQL'

### ISSUE THREAD

**Issue by an100** [ContinuumIO/blaze#997]
csv = CSV('iris.csv')  # Open the CSV file
t = Table(csv)         # Interact with CSV file using interactive Table object
t.schema

Out[51]:
dshape("""{
  sepal_length: ?float64,
  sepal_width: ?float64,
  petal_length: ?float64,
  petal_width: ?float64,
  species: ?string
  }""")

from blaze import SQL
sql = SQL('sqlite:///iris.db', 'iris', schema=t.schema)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-50-d8f1d286a231> in <module>()
----> 1 from blaze import SQL
      2 sql = SQL('sqlite:///iris.db', 'iris', schema=t.schema)

ImportError: cannot import name 'SQL'

I am trying to create a sqlite table with blaze according to blog post from M.Rocklin.
I have looked at odo. I am getting an erro too 

odo('iris.csv','sqlite:///iris.db')
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-43-2795f5d2a0b2> in <module>()
----> 1 odo('iris.csv','sqlite:///iris.db')

C:\Anaconda3\lib\site-packages\odo-0.3.1-py3.4.egg\odo\odo.py in odo(source, target, **kwargs)
     88     odo.append.append      - Add things onto existing things
     89     """
---> 90     return into(target, source, **kwargs)

C:\Anaconda3\lib\site-packages\multipledispatch\dispatcher.py in __call__(self, *args, **kwargs)
    161             self._cache[types] = func
    162         try:
--> 163             return func(*args, **kwargs)
    164 
    165         except MDNotImplementedError:

C:\Anaconda3\lib\site-packages\odo-0.3.1-py3.4.egg\odo\into.py in into_string_string(a, b, **kwargs)
    118 def into_string_string(a, b, **kwargs):
    119     r = resource(b, **kwargs)
--> 120     return into(a, r, **kwargs)
    121 
    122 

C:\Anaconda3\lib\site-packages\multipledispatch\dispatcher.py in __call__(self, *args, **kwargs)
    161             self._cache[types] = func
    162         try:
--> 163             return func(*args, **kwargs)
    164 
    165         except MDNotImplementedError:

C:\Anaconda3\lib\site-packages\odo-0.3.1-py3.4.egg\odo\into.py in into_string(uri, b, **kwargs)
    111         resource_ds = ds
    112 
--> 113     a = resource(uri, dshape=resource_ds, expected_dshape=ds, **kwargs)
    114     return into(a, b, dshape=ds, **kwargs)
    115 

C:\Anaconda3\lib\site-packages\odo-0.3.1-py3.4.egg\odo\regex.py in __call__(self, s, *args, **kwargs)
     62 
     63     def __call__(self, s, *args, **kwargs):
---> 64         return self.dispatch(s)(s, *args, **kwargs)
     65 
     66     @property

C:\Anaconda3\lib\site-packages\odo-0.3.1-py3.4.egg\odo\backends\sql.py in resource_sql(uri, *args, **kwargs)
    359     # We were not given a table name
    360     if ds:
--> 361         create_from_datashape(engine, ds)
    362     return engine
    363 

C:\Anaconda3\lib\site-packages\multipledispatch\dispatcher.py in __call__(self, *args, **kwargs)
    161             self._cache[types] = func
    162         try:
--> 163             return func(*args, **kwargs)
    164 
    165         except MDNotImplementedError:

C:\Anaconda3\lib\site-packages\odo-0.3.1-py3.4.egg\odo\backends\sql.py in create_from_datashape(engine, ds, **kwargs)
    175 @dispatch(sa.engine.base.Engine, DataShape)
    176 def create_from_datashape(engine, ds, **kwargs):
--> 177     assert isrecord(ds)
    178     metadata = metadata_of_engine(engine)
    179     for name, sub_ds in ds[0].dict.items():

AssertionError:

**Comment by mrocklin** [comment]
Blogposts go out of date.  The `SQL` object was retired a while ago.

Using `odo` is fine, but you'll have to specify a table name as well as a database name

    >>> odo('iris.csv', 'sqlite:///databasename.db::tablename')

See http://odo.pydata.org/en/latest/uri.html#separating-parts-with

**Comment by an100** [comment]
Thanks Matt. Odo works
